[package]
name = "heif-sys"
version = "0.1.0"
authors = ["oussama <md.oussama@gmail.com>"]
build = "build.rs"
edition = "2018"
links = "heif"

[dependencies]
bmp = "0.4"
mozjpeg = "0.8"

[build-dependencies]
bindgen = "0.45"